export const taobaoCookies = [
	{
		domain: ".taobao.com",
		expirationDate: 1593947049.363269,
		hostOnly: false,
		httpOnly: false,
		name: "_m_h5_tk",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: false,
		storeId: "0",
		value: "c5489bc5015a9c4e560cc5be558c0a63_1593350530313",
		id: 1,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1593947049.3633,
		hostOnly: false,
		httpOnly: false,
		name: "_m_h5_tk_enc",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: false,
		storeId: "0",
		value: "966fdd384d0061d134c231439882151e",
		id: 2,
	},
	{
		domain: ".taobao.com",
		hostOnly: false,
		httpOnly: true,
		name: "_samesite_flag_",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: true,
		storeId: "0",
		value: "true",
		id: 3,
	},
	{
		domain: ".taobao.com",
		hostOnly: false,
		httpOnly: false,
		name: "_tb_token_",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: true,
		storeId: "0",
		value: "e860b5e8966bb",
		id: 4,
	},
	{
		domain: ".taobao.com",
		expirationDate: 3626384460.278366,
		hostOnly: false,
		httpOnly: false,
		name: "ali_apache_id",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: false,
		storeId: "0",
		value: "11.81.19.190.1593361418203.425082.9",
		id: 5,
	},
	{
		domain: ".taobao.com",
		expirationDate: 2224082917,
		hostOnly: false,
		httpOnly: false,
		name: "cna",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: false,
		storeId: "0",
		value: "kidMF5zWbQQCATFeWO6xf27r",
		id: 6,
	},
	{
		domain: ".taobao.com",
		hostOnly: false,
		httpOnly: true,
		name: "cookie2",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: true,
		storeId: "0",
		value: "1f43e33d4a69e189131a9785489b06d0",
		id: 7,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1905490804.513549,
		hostOnly: false,
		httpOnly: true,
		name: "enc",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: false,
		storeId: "0",
		value:
			"zsqqF7O%2FB1uYD%2FM%2FySWuCjbuTKeWfeqJg3zM3zFzdVy89gbyPAPLLyQU17a2YwYYgXg7WdYaQCraOKc0DIXq5w%3D%3D",
		id: 8,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1624927715.414027,
		hostOnly: false,
		httpOnly: false,
		name: "hng",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: false,
		storeId: "0",
		value: "CN%7Czh-CN%7CCNY%7C156",
		id: 9,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1608914930,
		hostOnly: false,
		httpOnly: false,
		name: "isg",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: false,
		storeId: "0",
		value: "BM3NEBear1Q1tQtHB09zK2XN3OlHqgF83BJmmA9SxWTTBuy41Pv6TSfXcJpgwBk0",
		id: 10,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1608914930,
		hostOnly: false,
		httpOnly: false,
		name: "l",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: false,
		storeId: "0",
		value:
			"eBgryrV4QfqrlOPYBO5BPurza77TrIRb8rVzaNbMiInca6iFNF98JNQDW47yldtjgt5Eue-rb3kJjRHJ8Rz38FkDBeYCSCK53hv68e1..",
		id: 11,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1593996515.413606,
		hostOnly: false,
		httpOnly: false,
		name: "mt",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: false,
		storeId: "0",
		value: "ci=0_0",
		id: 12,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1624926386.378235,
		hostOnly: false,
		httpOnly: true,
		name: "sgcookie",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: false,
		storeId: "0",
		value: "EzP8j%2F9Amn5eO8Q4XvbUc",
		id: 13,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1601166386.378437,
		hostOnly: false,
		httpOnly: false,
		name: "t",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: false,
		storeId: "0",
		value: "b5ab8a877f008f6d8e1d82a13a07a088",
		id: 14,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1608913509,
		hostOnly: false,
		httpOnly: false,
		name: "tfstk",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: false,
		storeId: "0",
		value: "c-QABuDEW82mdwORTiEkfSNWFv2ha9lvIj9tW5P3-Bn7ifu-Ps21-wKvqoOZHUFR.",
		id: 15,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1621234806,
		hostOnly: false,
		httpOnly: false,
		name: "thw",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: false,
		storeId: "0",
		value: "cn",
		id: 16,
	},
	{
		domain: ".taobao.com",
		expirationDate: 1624927715.414083,
		hostOnly: false,
		httpOnly: false,
		name: "tracknick",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: false,
		storeId: "0",
		value: "",
		id: 17,
	},
	{
		domain: "v.taobao.com",
		hostOnly: true,
		httpOnly: false,
		name: "_tb_token_",
		path: "/v/content",
		sameSite: "unspecified",
		secure: false,
		session: true,
		storeId: "0",
		value: "undefined",
		id: 18,
	},
	{
		domain: "v.taobao.com",
		hostOnly: true,
		httpOnly: false,
		name: "_tb_token_",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: true,
		storeId: "0",
		value: "undefined",
		id: 19,
	},
	{
		domain: "v.taobao.com",
		hostOnly: true,
		httpOnly: true,
		name: "XSRF-TOKEN",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: true,
		storeId: "0",
		value: "84cbbab9-847d-4dcc-9662-659ab0570ef1",
		id: 20,
	},
];

export const yinghuochongCookies = [
	{
		domain: ".yihoc.com",
		hostOnly: false,
		httpOnly: false,
		name: "uid",
		path: "/",
		sameSite: "no_restriction",
		secure: true,
		session: true,
		storeId: "0",
		value: "66256",
		id: 1,
	},
];
export const darenjiCookies = [
	{
		domain: ".darenji.com",
		hostOnly: false,
		httpOnly: false,
		name: "Hm_lpvt_799e19d1d6d8a5aba11e78bc8f77816b",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: true,
		storeId: "0",
		value: "1593397485",
		id: 1,
	},
	{
		domain: ".darenji.com",
		expirationDate: 1624933484,
		hostOnly: false,
		httpOnly: false,
		name: "Hm_lvt_799e19d1d6d8a5aba11e78bc8f77816b",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: false,
		storeId: "0",
		value: "1593248009,1593276863,1593358367",
		id: 2,
	},
	{
		domain: "www.darenji.com",
		expirationDate: 1593444766.402025,
		hostOnly: true,
		httpOnly: false,
		name: "PHPSESSID",
		path: "/",
		sameSite: "unspecified",
		secure: false,
		session: false,
		storeId: "0",
		value: "84hfcjbaggvi4q1jn40kb0rds1",
		id: 3,
	},
];
